version: '3.4'

services:
  php:
    build:
      context: .
      target: sylius_order_now_plugin_php
    image: nedac/sylius_order_now_plugin_php:latest
    environment:
      - APP_ENV=test
      - DATABASE_URL=mysql://sylius:order_now@127.0.0.1:3306/sylius_order_now
    volumes:
      - .:/srv/sylius
    network_mode: host

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sylius_order_now
      - MYSQL_USER=sylius
      - MYSQL_PASSWORD=order_now
    ports:
      - "3306:3306"
    network_mode: host

  nginx:
    build:
      context: .
      target: sylius_order_now_plugin_nginx
    image: nedac/sylius_order_now_plugin_nginx:latest
    volumes:
      - .:/srv/sylius
    ports:
      - "8080:8080"
    network_mode: host

  nodejs:
    build:
      context: .
      target: sylius_order_now_plugin_nodejs
    image: nedac/sylius_order_now_plugin_nodejs:latest
    environment:
      - GULP_ENV=dev
    volumes:
      - .:/srv/sylius
    network_mode: host

  chrome:
    image: selenium/standalone-chrome-debug:latest
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "5900:5900"
    network_mode: host
